micronaut:
  application:
    name: fuel
  server:
    port: 9090
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

---

datasources:
  default:
    url: jdbc:mysql://localhost:3306/sms
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'toor'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - 'com.project.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        bytecode:
          provider: none